"use client";

import { Crosshair, Target } from "lucide-react";
import type { AnalysisResult } from "@/lib/types";
import { CardShell, StatePill, StatRow } from "./CardShell";
import { fmtPct, fmtPrice } from "@/lib/format";

export default function TradePlanCard({ analysis }: { analysis: AnalysisResult }) {
  const { plan, quote, pattern } = analysis;
  const precision = quote.last < 1 ? 4 : 2;
  const pctFrom = (v: number) => ((v - plan.entry) / plan.entry) * 100;

  const ladder = [
    { label: "TARGET 2 · 1.618×", price: plan.t2, tone: "text-bull-soft", border: "border-bull/40", bg: "bg-bull/10", dash: true, emoji: "🎯" },
    { label: "TARGET 1 · MEASURED", price: plan.t1, tone: "text-bull-soft", border: "border-bull/40", bg: "bg-bull/10", dash: true, emoji: "🎯" },
    { label: pattern.neckline > plan.stop ? "NECKLINE / RESISTANCE" : "NECKLINE", price: pattern.neckline, tone: "text-bear-soft", border: "border-bear/40", bg: "bg-bear/5", dash: false, emoji: "⛔" },
    { label: plan.breakoutMode ? "ENTRY · BUY-STOP" : "ENTRY · MARKET FLOW", price: plan.entry, tone: "text-sky", border: "border-sky/50", bg: "bg-sky/10", dash: false, emoji: "📍" },
    { label: "STOP-LOSS · PIVOT LOW", price: plan.stop, tone: "text-bear-soft", border: "border-bear/50", bg: "bg-bear/10", dash: true, emoji: "🛑" },
  ].sort((a, b) => b.price - a.price);

  return (
    <CardShell
      icon={Target}
      title="AUTOMATED TRADE PLAN"
      step="EXECUTION BLUEPRINT"
      accent="#34d399"
      right={
        <StatePill tone={plan.breakoutMode ? "gold" : "bull"}>
          {plan.breakoutMode ? "AWAITING BREAKOUT" : "BREAKOUT LIVE"}
        </StatePill>
      }
    >
      {/* price ladder */}
      <div className="space-y-1.5">
        {ladder.map((row) => (
          <div
            key={row.label}
            className={`num flex items-center justify-between rounded-lg border px-3 py-2 ${row.border} ${row.bg}`}
          >
            <span className="text-[10px] font-bold tracking-[0.12em] text-muted">
              {row.emoji} {row.label}
              {row.dash && <span className="ml-1.5 text-faint">- - -</span>}
            </span>
            <span className="flex items-baseline gap-2">
              <span className={`text-[13px] font-black ${row.tone}`}>
                {fmtPrice(row.price, precision)}
              </span>
              <span className="w-14 text-right text-[9.5px] text-faint">
                {fmtPct(pctFrom(row.price), 1)}
              </span>
            </span>
          </div>
        ))}
      </div>

      <div className="mt-3 grid grid-cols-3 gap-2">
        <div className="rounded-lg border border-line-soft bg-well/60 px-2.5 py-2 text-center">
          <div className="num text-[9px] tracking-[0.18em] text-faint">R:R → T1</div>
          <div className="num mt-0.5 text-[15px] font-black text-bull-soft">
            {plan.rr1.toFixed(2)}
          </div>
        </div>
        <div className="rounded-lg border border-line-soft bg-well/60 px-2.5 py-2 text-center">
          <div className="num text-[9px] tracking-[0.18em] text-faint">R:R → T2</div>
          <div className="num mt-0.5 text-[15px] font-black text-bull-soft">
            {plan.rr2.toFixed(2)}
          </div>
        </div>
        <div className="rounded-lg border border-line-soft bg-well/60 px-2.5 py-2 text-center">
          <div className="num text-[9px] tracking-[0.18em] text-faint">RISK</div>
          <div className="num mt-0.5 text-[15px] font-black text-bear-soft">
            {plan.riskPct.toFixed(1)}%
          </div>
        </div>
      </div>

      <div className="mt-2 border-t border-line-soft/60 pt-1.5">
        <StatRow
          label="ATR(14) BUFFER"
          value={`± ${fmtPrice(analysis.atr, precision)} / BAR`}
          valueClass="text-muted"
        />
        <StatRow
          label="SIGNAL ARROWS ON CHART"
          value={`${analysis.signals.length} IN WINDOW`}
          valueClass={analysis.signals.length ? "text-bull-soft" : "text-faint"}
        />
        <StatRow
          label="PLAN MODE"
          value={plan.breakoutMode ? "BUY-STOP ABOVE NECKLINE" : "TREND CONTINUATION"}
          valueClass="text-sky"
        />
      </div>

      <p className="num mt-2 flex items-start gap-1.5 text-[9.5px] leading-relaxed tracking-wide text-faint">
        <Crosshair className="mt-px h-3 w-3 shrink-0" />
        SIMULATED PAPER PLAN — GENERATED BY THE STRATEGY ENGINE, NOT INVESTMENT ADVICE.
      </p>
    </CardShell>
  );
}
